services:
  wordle-backend:
    image: ttl.sh/eedf9e53-d5ba-4624-9ab8-6cd09b74fcf9:1h
    ports:
      - 9191:8000
    restart: unless-stopped
  wordle-frontend:
    image: ttl.sh/d6601460-3cf6-4184-bf30-a863b38398cc:1h
    ports:
      - 9192:3000
    depends_on:
      - wordle-backend
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=http://wordle-backend:8000
      - VITE_API_BASE=http://localhost:8000
    restart: unless-stopped
