# WIP Wordle Aid - Docker Compose File
services:
  wordle-aid:
    container_name: wordle-aid
    stdin_open: true    # equivalent to -i
    tty: true           # equivalent to -t
    image: gitlab-registry.kripso-world.com/kripso/wordle_aid:latest
    # privileged: false
    # user: 1000:1000
    networks:
      cloudflare: {}

    environment:
      PROD_MODE_ENABLED: true
      RAPID_API_KEY: "${RAPID_API_KEY}"
      RAPID_API_HOST: "${RAPID_API_HOST}"
      DB_ROOT_PATH: /home/wordle_helper/database
    volumes:
      - /docker_volumes/wordle_helper/database:/home/wordle_helper/database
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  cloudflare:
    external: true