services:
  wordle-aid:
    container_name: wordle-aid
    image: gitea.kripso-world.com/kripso/wordle_aid:latest
    privileged: false
    user: 1234:1234
    ports:
      - 9192:80
      - 9193:8000
    environment:
      - NODE_ENV=production
      - PUBLIC_API_BASE=http://192.168.1.201:9193
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
